import read_doc as rd

globalInfo = rd.collectGoodDataFromTab(rd.readFile())


scoreSlytherin = TetaSlytherinArithmancy * NoteElveArithmancy + TetaSlytherinAstronomy * NoteElveAstronomy + TetaSlytherinHerbology * NoteElveHerbology + TetaSlytherinDefense * NoteElveDefense + TetaSlytherinDivination * NoteElveDivination + TetaSlytherinMuggle * NoteElveMuggle + TetaSlytherinAncient * NoteElveAncient + TetaSlytherinHistory * NoteElveHistory + TetaSlytherinTransfiguration * NoteElveTransfiguration + TetaSlytherinPotions * NoteElvePotions + TetaSlytherinCare * NoteElveCare + TetaSlytherinCharms * NoteElveCharms + TetaSlytherinFlying * NoteElveFlying
scoreGryffindor = TetaGryffindorArithmancy * NoteElveArithmancy + TetaGryffindorAstronomy * NoteElveAstronomy + TetaGryffindorHerbology * NoteElveHerbology + TetaGryffindorDefense * NoteElveDefense + TetaGryffindorDivination * NoteElveDivination + TetaGryffindorMuggle * NoteElveMuggle + TetaGryffindorAncient * NoteElveAncient + TetaGryffindorHistory * NoteElveHistory + TetaGryffindorTransfiguration * NoteElveTransfiguration + TetaGryffindorPotions * NoteElvePotions + TetaGryffindorCare * NoteElveCare + TetaGryffindorCharms * NoteElveCharms + TetaGryffindorFlying * NoteElveFlying
scoreHufflepuff = TetaHufflepuffArithmancy * NoteElveArithmancy + TetaHufflepuffAstronomy * NoteElveAstronomy + TetaHufflepuffHerbology * NoteElveHerbology + TetaHufflepuffDefense * NoteElveDefense + TetaHufflepuffDivination * NoteElveDivination + TetaHufflepuffMuggle * NoteElveMuggle + TetaHufflepuffAncient * NoteElveAncient + TetaHufflepuffHistory * NoteElveHistory + TetaHufflepuffTransfiguration * NoteElveTransfiguration + TetaHufflepuffPotions * NoteElvePotions + TetaHufflepuffCare * NoteElveCare + TetaHufflepuffCharms * NoteElveCharms + TetaHufflepuffFlying * NoteElveFlying
scoreRavenclaw = TetaRavenclawArithmancy * NoteElveArithmancy + TetaRavenclawAstronomy * NoteElveAstronomy + TetaRavenclawHerbology * NoteElveHerbology + TetaRavenclawDefense * NoteElveDefense + TetaRavenclawDivination * NoteElveDivination + TetaRavenclawMuggle * NoteElveMuggle + TetaRavenclawAncient * NoteElveAncient + TetaRavenclawHistory * NoteElveHistory + TetaRavenclawTransfiguration * NoteElveTransfiguration + TetaRavenclawPotions * NoteElvePotions + TetaRavenclawCare * NoteElveCare + TetaRavenclawCharms * NoteElveCharms + TetaRavenclawFlying * NoteElveFlying
